### ISSUE TITLE
运行npm i命令报错

### ISSUE THREAD

**Issue by zhoubhin** [wmfe/xcui#203]
在项目根目录下，运行 `npm i`命令，提示以下错误：
`Error: sha1-7ru3/8XYBR7xGXhFP8gTUtnyXXM= integrity checksum failed when using sha1: wanted sha1-7ru3/8XYBR7xGXhFP8gTUtnyXXM= but got sha1-OzGx7pK0sgDgiwgHMOjDFxhvtAQ=. (4054 bytes)
    at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:275:19)
    at emitNone (events.js:111:20)
    at Transform.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by clancyz** [comment]
试着清下缓存。或者使用yarn
```bash
$ rm -rf node_modules
$ rm package-lock.json
$ npm cache clean --force
$ npm i 
```

**Comment by zhoubhin** [comment]
@clancyz 
现在运行`npm i`命令不再报错了，问题解决🙏
